# Generated by Django 4.2.2 on 2025-08-14 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the alumni', max_length=100)),
                ('headshot', models.ImageField(help_text='Professional headshot photo', upload_to='alumni_photos/')),
                ('bio', models.TextField(help_text='Brief biography and background')),
                ('current_endeavors', models.TextField(help_text="Current job, projects, or what they're working on now")),
                ('email', models.EmailField(help_text='Contact email address', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('major', models.CharField(help_text='Major studied at UVA', max_length=100)),
                ('graduation_year', models.PositiveIntegerField(help_text='Year graduated from UVA')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL (optional)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this alumni prominently on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'ordering': ['-graduation_year', 'name'],
            },
        ),
    ]
