# Generated by Django 4.2.2 on 2025-08-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='current_endeavors',
        ),
        migrations.AddField(
            model_name='alumni',
            name='company',
            field=models.CharField(default='default', help_text='Current company, university, or organization', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='position',
            field=models.CharField(default='default', help_text='Current job title or position', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='shpe_status',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('vice_president', 'Vice President'), ('co_president', 'Co-President'), ('president', 'President'), ('social_chair', 'Social Chair'), ('marketing', 'Marketing'), ('corporate_relations', 'Corporate Relations'), ('community_outreach', 'Community Outreach'), ('convention_chair', 'Convention Chair'), ('first_year_rep', 'First Year Representative')], default='member', help_text='Role they held in SHPE UVA', max_length=50),
        ),
    ]
