# Generated by Django 4.2.2 on 2025-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_alumni_current_endeavors_alumni_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='shpe_status',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('vice_president', 'Vice President'), ('co_president', 'Co-President'), ('president', 'President'), ('social_chair', 'Social Chair'), ('marketing', 'Marketing'), ('corporate_relations', 'Corporate Relations'), ('community_outreach', 'Community Outreach'), ('convention_chair', 'Convention Chair'), ('first_year_rep', 'First Year Representative'), ('spiderman', 'WebMaster')], default='member', help_text='Role they held in SHPE UVA', max_length=50),
        ),
    ]
