# Generated by Django 4.2.2 on 2025-08-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_alumni_shpe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_current_exec',
            field=models.BooleanField(default=False, help_text='Currently serving on the executive board'),
        ),
    ]
