# Generated by Django 4.2.2 on 2025-08-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alumni_is_current_exec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='company',
            field=models.CharField(blank=True, help_text='Current company, university, or organization (optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='headshot',
            field=models.ImageField(blank=True, help_text='Professional headshot photo (optional) - Will be automatically compressed', null=True, upload_to='alumni_photos/'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='position',
            field=models.CharField(blank=True, help_text='Current job title or position (optional)', max_length=200, null=True),
        ),
    ]
